name: Production Deployment

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      IMAGE_TAG: prod-${{ github.sha }}

    steps:
    # -------------------------
    # Checkout code
    # -------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------
    # Configure AWS for ECR & deploy
    # -------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN_PRODUCTION }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f app/Dockerfile app


    - name: Push Docker image to ECR
      run: |
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    # -------------------------
    # Deploy to EKS
    # -------------------------
    #- name: Update kubeconfig for EKS
      #run: |
        #aws eks update-kubeconfig --region $AWS_REGION --name production-cluster

    #- name: Deploy to EKS
      #run: |
        #kubectl set image deployment/flask-app flask-app=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG -n production || \
        #kubectl create deployment flask-app --image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG -n production
        #kubectl rollout status deployment/flask-app -n production
