name: Staging Deployment

on:
  push:
    branches: [ staging ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: staging-${{ github.sha }}
      CLUSTER_NAME: devops-assessment
      K8S_NAMESPACE: staging

    steps:
    # -------------------------
    # Checkout
    # -------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------
    # Configure AWS (OIDC)
    # -------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN_STAGING }}
        aws-region: ${{ secrets.AWS_REGION }}

    # -------------------------
    # Login to ECR
    # -------------------------
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # -------------------------
    # Build & Push Image
    # -------------------------
    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f app/Dockerfile app

    - name: Push Docker image to ECR
      run: |
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
        docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    # -------------------------
    # Authenticate kubectl to EKS
    # -------------------------
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME

    # -------------------------
    # Deploy to Kubernetes
    # -------------------------
    - name: Create namespace if not exists
      run: |
        kubectl create namespace $K8S_NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy application
      run: |
        kubectl -n $K8S_NAMESPACE create deployment flask-app \
          --image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl -n $K8S_NAMESPACE expose deployment flask-app \
          --type=LoadBalancer --port=80 --target-port=5000 \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl rollout status deployment/flask-app -n $K8S_NAMESPACE
